### ISSUE TITLE
Rename to RefactoringProcessor

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Common-Eclipse-Java-Refactoring-Framework#10]
https://github.com/ponder-lab/Common-Eclipse-Java-Refactoring-Framework/blob/7c0cb822cb89e59feb23c4ec7a305fd3d8d08616/edu.cuny.citytech.refactoring.common.core/src/edu/cuny/citytech/refactoring/common/core/refactorings/CommonRefactoringProcessor.java

**Comment by saledouble** [comment]
The commit:  b28db8c
