### ISSUE TITLE
Rename package to edu.cuny.citytech.refactoring.common.core

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Common-Eclipse-Java-Refactoring-Framework#8]
https://github.com/ponder-lab/Common-Eclipse-Java-Refactoring-Framework/blob/7c0cb822cb89e59feb23c4ec7a305fd3d8d08616/edu.cuny.citytech.refactoring.common.core/src/edu/cuny/citytech/refactoring/common/core/refactorings/CommonProcessorBasedRefactoring.java#L1

Please remove the second `refactorings`.

**Comment by saledouble** [comment]
The commit:  d904271

**Comment by saledouble** [comment]
Should I do the same thing for the processor class?
https://github.com/ponder-lab/Common-Eclipse-Java-Refactoring-Framework/blob/7c0cb822cb89e59feb23c4ec7a305fd3d8d08616/edu.cuny.citytech.refactoring.common.core/src/edu/cuny/citytech/refactoring/common/core/refactorings/CommonRefactoringProcessor.java#L1
