### ISSUE TITLE
Rename to `ProcessorBasedRefactoring`

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Common-Eclipse-Java-Refactoring-Framework#9]
https://github.com/ponder-lab/Common-Eclipse-Java-Refactoring-Framework/blob/7c0cb822cb89e59feb23c4ec7a305fd3d8d08616/edu.cuny.citytech.refactoring.common.core/src/edu/cuny/citytech/refactoring/common/core/refactorings/CommonProcessorBasedRefactoring.java#L1

Please remove the second `refactorings`.

**Comment by saledouble** [comment]
The commit:  2afb8d5
